---
- name: Check if Bloodhound is already installed
  ansible.builtin.stat:
    path: "{{ ludus_bloodhound_ce_install_path }}/docker-compose.yml"
  register: bh_installed

- name: End the play if Bloodhound is already installed - to run this play again remove the directory {{ ludus_bloodhound_ce_install_path }}
  ansible.builtin.meta: end_host
  when: bh_installed.stat.exists

- name: Make bloodhound directory
  become: true
  ansible.builtin.file:
    path: "{{ ludus_bloodhound_ce_install_path }}"
    state: directory
    mode: "0755"

- name: Copy the docker-compose.yml file
  become: true
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ ludus_bloodhound_ce_install_path }}/docker-compose.yml"
    mode: "0644"

- name: Set the andmin password var
  ansible.builtin.set_fact:
    ludus_bloodhound_admin_password: "{{ lookup('community.general.random_string', length=15, min_lower=1, min_upper=1, min_numeric=1, min_special=1, override_special='!@#$%^&*') }}"
  when: ludus_bloodhound_admin_password is undefined or ludus_bloodhound_admin_password == None

- name: Copy the .env template to the host
  ansible.builtin.template:
    src: env.j2
    dest: "{{ ludus_bloodhound_ce_install_path }}/.env"
    mode: "0600"

- name: Write the password to a file on the remote host
  ansible.builtin.lineinfile:
    path: "{{ ludus_bloodhound_ce_install_path }}/bloodhound_admin_password.txt"
    line: "{{ ludus_bloodhound_admin_password }}"
    mode: "0600"
    create: true

- name: If ludus_bloodhound_listen_only_localhost is false, create .env file
  ansible.builtin.lineinfile:
    path: "{{ ludus_bloodhound_ce_install_path }}/.env"
    line: "BLOODHOUND_HOST='0.0.0.0'"
    mode: "0644"
  when: not ludus_bloodhound_listen_only_localhost

- name: Start Bloodhound
  become: true
  ansible.builtin.shell:
    cmd: |
      cd {{ ludus_bloodhound_ce_install_path }}
      docker compose up -d

- name: Alert
  ansible.builtin.debug:
    msg: |
      Bloodhound is up and running. Access it at http://{{ ansible_host }}:{{ ludus_bloodhound_port }} Access with: admin:{{ ludus_bloodhound_admin_password }}